Documentation/unity how to collider and rendering order
Gamify-IT/docs pull request #62
Opened 2022-06-30 10:08 UTC by IlijazM

2022-06-30 10:19 UTC, LeviUniAcc commented
really nice doku, i want to look for a better solution of the player render situation because changeing the pivot is a clunky solution.

2022-06-30 11:59 UTC, LeviUniAcc approved these changes

2022-07-01 09:38 UTC, delvh requested changes

2022-07-06 09:37 UTC, delvh commented
@IlijazM should I take over the branch and PR?
It is stale and should be merged soon

2022-07-08 17:30 UTC, delvh approved these changes

2022-07-08 17:30 UTC, merged