ADR: How to spell "ID" as variable name
Gamify-IT/docs pull request #92
Opened 2022-07-22 15:10 UTC by delvh

2022-07-22 15:24 UTC, marlau97 approved these changes

2022-07-22 15:35 UTC, cdingm approved these changes

2022-07-22 16:04 UTC, Gr33ndev approved these changes

2022-07-22 16:12 UTC, maexled approved these changes

2022-07-22 17:09 UTC, IlijazM approved these changes

2022-07-22 17:58 UTC, madebyTimo approved these changes

2022-07-26 10:56 UTC, cdingm approved these changes

2022-07-26 11:53 UTC, Gr33ndev requested changes

2022-07-26 11:53 UTC, Gr33ndev commented on adr/2022-07-26-spelling-of-id.md
> +- `id` if there is no prefix, `-Id` for variables, `-ID` for class names  (-> `lectureId`, `lectureDto`, `LectureDTO`)
```suggestion
- `id` if there is no prefix, `-Id` for variables, `-ID` for class names  (-> `lectureId`, `lectureDTO`, `LectureDTO`)
```

2022-07-26 11:53 UTC, Gr33ndev commented on adr/2022-07-26-spelling-of-id.md
> +- Conforms with the way many (Java) libraries handle it
```suggestion
## Contra 3)

- Inconsistent and you would have to change everything
```

2022-07-26 11:53 UTC, Gr33ndev commented on adr/2022-07-26-spelling-of-id.md
> +- Confusing to enforce
```suggestion
## Pro 4)

- Uniform and you would not have to change anything
```

2022-07-26 11:57 UTC, delvh commented on adr/2022-07-26-spelling-of-id.md
> +
```suggestion

## Contra 3)

- Inconsistent and you would have to change everything

```

2022-07-26 12:05 UTC, Gr33ndev approved these changes

2022-07-26 12:06 UTC, WuestFlorian approved these changes

2022-07-26 12:07 UTC, merged